# Generated by Django 4.1.3 on 2024-03-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(related_name='projects', to='core.projectimg'),
        ),
    ]
