# Generated by Django 4.1.3 on 2024-03-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectimg_rename_image_projects_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='images',
        ),
        migrations.DeleteModel(
            name='ProjectImg',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
    ]
