# Generated by Django 4.1.3 on 2024-03-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectimage_remove_projects_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='product',
            new_name='project',
        ),
    ]
